apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-01-23T20:47:03Z"
  name: carts-canary
  resourceVersion: "1023393"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 825ce112-3e21-11ea-84d4-42010a80010c
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
